GET http://localhost:8000/products/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2NTMzMDU1LCJpYXQiOjE3NzY1MzI3NTUsImp0aSI6IjZjODdiZTVhNDc2ZjQ4YTQ5ZDRkYmM1ZTZlZmIyZjMxIiwidXNlcl9pZCI6IjIifQ.MnSZYJsH5tZvDoxrPZwXy5oLLiZe7h2TqaPHF19ALYE

POST http://localhost:8000/api/token/
Content-Type: application/json

{
  "username": "sami",
  "password": "test@123"
}

### Create a New Product
POST http://localhost:8000/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2NTMzMDU1LCJpYXQiOjE3NzY1MzI3NTUsImp0aSI6IjZjODdiZTVhNDc2ZjQ4YTQ5ZDRkYmM1ZTZlZmIyZjMxIiwidXNlcl9pZCI6IjIifQ.MnSZYJsH5tZvDoxrPZwXy5oLLiZe7h2TqaPHF19ALYE
\
{
    "name": "New Smartphone",
    "description": "A high-end smartphone with a great camera.",
    "price": 799.99,
    "stock": 50
}

### Get Product Information
GET http://localhost:8000/orders/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2NTMzMDU1LCJpYXQiOjE3NzY1MzI3NTUsImp0aSI6IjZjODdiZTVhNDc2ZjQ4YTQ5ZDRkYmM1ZTZlZmIyZjMxIiwidXNlcl9pZCI6IjIifQ.MnSZYJsH5tZvDoxrPZwXy5oLLiZe7h2TqaPHF19ALYE


###
POST http://localhost:8000/auth/register/
Content-Type: application/json

{
  "username": "newuser",
  "email": "newuser@example.com",
  "password": "securepassword"
}